language: node_js

node_js: node

script:
- npm run build

deploy:
  provider: npm
  email: rob@calculem.us
  skip-cleanup: true
  api_key:
    secure: HALdQTsQbo/YX4Rf81XnXsKiW3JL8VI/QhxJCRn0Vm3y5jW0NYbs+Fz9WrDnV6aMeizUQ4g0ILnJGZvmAZUk+q2YGfV3tIxECLb9UeL6ENfuWequi0teNiz8IZvzcTP7gbc/NYFrjvks3qh+zTQjkuf4yXz9l6YEMFUUB3QEVbu7hAnk6hQcL+/OF40rTXuVQMRqKyOZGrfchQz97Gy2Z2AFIoVzbzUh07UwjP+0EJJ0oYyY6KpWOaH5yuJcnEL4k3N1/14NUZkrHe54Utwq05Ta1DZmqDHhQfORO5lsVSXgrFZ+HHp6hkmMT15U24ucyQT0Tnk6zF6E9q9DeieFfX2zg39Yg80v15akZXu9729dyTGa8Fbp8rl1+V9yMvIkz7qPGS953hTvbhx2yfZftOJ1NFRrF2bTevDi8IyekY3qteP5snGCSE55ZDqwW9QYil7R6ojsSl5O0kv9SJHvCvPmAv1xwuWe8uy4qNbqOUIaPofkRlenvaMyiOtWnjMMyoG7ixzM1G3lev1W6b1qAl/gwPdS8N9oZi/Y6u1Xb6lDsU+SVs6uVtXPnUTh7ZDl0YCpfpqi/asM9r8okiqirzJZTB2kCbPvq0b34U1EVulXnNWrCb3JDGgt3U8Njln1xaavpkvwccVNJFYvrtPaxBwcqLwgWPQ4v7tQvBfohE0=
  on:
    repo: retutch/tutch-codemirror
    branch: master